name: Deploy React Application

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v3
      - name: Generate Firebase SDK config
        run: |
          echo "${{ secrets.GCP_KEY }}" >> /opt/gcp_key.json
          export GOOGLE_APPLICATION_CREDENTIALS=/opt/gcp_key.json
          npm install -g firebase-tools
          firebase use --add simple-budget-c19f0
          firebase apps:sdkconfig web --json > src/firebaseConfig.json
      - name: build project
        run: |
          npm ci
          npm run build
      - name: deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./dist-build